### ISSUE TITLE
breaking change in 2.0.3

### ISSUE THREAD

**Issue by rittneje** [hamcrest/PyHamcrest#214]
With v2.0.2 installed, I can do `from hamcrest import matcher`. With v2.0.3, this line fails.

**Comment by offbyone** [comment]
Accurate. This is a small, but probably not-going-to-be-reverted change in the import hierarchy; we are not flattening the previously-accidentally-exposed module hierarchy of the library, only the intentional types. 

If you want to import `hamcrest.core.matcher` you need to import it from `hamcrest.core`; the top level aggregator is only surfacing the documented matcher functions now. I know this will entail a small code change, but that structure was not intended to be propagated upward in that fashion, and that's now been fixed.
